services:
  slackfrontend:
    build: .
    ports:
      - "888:3000"    
    depends_on:
      - db
  nodebackend: 
    build: server/
    ports: 
      - "9000:9000"    #external:internal 
    depends_on:
      - db
  db:
    volumes:
      - slack_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"  
volumes:
   slack_db:
